In [26]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
from google.colab import files
Uploaded=files.upload()

Saving Priyanshu Jain - Classification Dataset1.csv to Priyanshu Jain - Classification Dataset1.csv


In [42]:
dataset= pd.read_csv('Priyanshu Jain - Classification Dataset1.csv')
dataset


Surname  CreditScore Geography  ... IsActiveMember  EstimatedSalary  Exited
0      Hargrave          619    France  ...            1.0        101348.88       1
1          Hill          608     Spain  ...            1.0        112542.58       0
2          Onio          502    France  ...            0.0        113931.57       1
3          Boni          699    France  ...            0.0         93826.63       0
4      Mitchell          850     Spain  ...            1.0         79084.10       0
...         ...          ...       ...  ...            ...              ...     ...
4498   Obijiaku          771    France  ...            0.0         96270.64       0
4499  Johnstone          516    France  ...            1.0        101699.77       0
4500        Liu          709    France  ...            1.0         42085.58       1
4501  Sabbatini          772    France  ...            0.0         92888.52       1
4502     Walker          792    France  ...            0.0         38190.78       0

[4503 rows x 11 columns]

In [43]:
#Check Missing Data
dataset.isnull().sum()

Surname             0
CreditScore         0
Geography           0
Gender              5
Age                 6
Tenure              3
Balance            15
HasCrCard           4
IsActiveMember      2
EstimatedSalary     9
Exited              0
dtype: int64

In [44]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4503 entries, 0 to 4502
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Surname          4503 non-null   object 
 1   CreditScore      4503 non-null   int64  
 2   Geography        4503 non-null   object 
 3   Gender           4498 non-null   object 
 4   Age              4497 non-null   float64
 5   Tenure           4500 non-null   float64
 6   Balance          4488 non-null   float64
 7   HasCrCard        4499 non-null   float64
 8   IsActiveMember   4501 non-null   float64
 9   EstimatedSalary  4494 non-null   float64
 10  Exited           4503 non-null   int64  
dtypes: float64(6), int64(2), object(3)
memory usage: 387.1+ KB


In [54]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,1:10].values
# Extracting dependent variable:
y = dataset.iloc[:,10].values

In [69]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NaN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:,3:9]) 
#Replacing missing data with the calculated mean value  
X[:,3:9]= imputer.transform(X[:,3:9])  

In [70]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NaN, strategy= 'constant', fill_value='female', verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 2:3]) 
#Replacing missing data with the constant value  
X[:, 2:3]= imputer.transform(X[:,2:3])  

In [71]:
print(X)

[[619 0 'Female' ... 1.0 1.0 101348.88]
 [608 1 'Female' ... 0.0 1.0 112542.58]
 [502 0 'Female' ... 1.0 0.0 113931.57]
 ...
 [709 0 'Female' ... 0.0 1.0 42085.58]
 [772 0 'Male' ... 1.0 0.0 92888.52]
 [792 0 'Female' ... 1.0 0.0 38190.78]]


In [72]:
print(y)

[1 0 1 ... 1 1 0]


In [73]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])

In [74]:
print(X)

[[619 0 'Female' ... 1.0 1.0 101348.88]
 [608 1 'Female' ... 0.0 1.0 112542.58]
 [502 0 'Female' ... 1.0 0.0 113931.57]
 ...
 [709 0 'Female' ... 0.0 1.0 42085.58]
 [772 0 'Male' ... 1.0 0.0 92888.52]
 [792 0 'Female' ... 1.0 0.0 38190.78]]


In [75]:
print(X)

[[619 0 'Female' ... 1.0 1.0 101348.88]
 [608 1 'Female' ... 0.0 1.0 112542.58]
 [502 0 'Female' ... 1.0 0.0 113931.57]
 ...
 [709 0 'Female' ... 0.0 1.0 42085.58]
 [772 0 'Male' ... 1.0 0.0 92888.52]
 [792 0 'Female' ... 1.0 0.0 38190.78]]


In [76]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 2] = labelencoder_X.fit_transform(X[:, 2])

In [77]:
print(X)

[[619 0 0 ... 1.0 1.0 101348.88]
 [608 1 0 ... 0.0 1.0 112542.58]
 [502 0 0 ... 1.0 0.0 113931.57]
 ...
 [709 0 0 ... 0.0 1.0 42085.58]
 [772 0 1 ... 1.0 0.0 92888.52]
 [792 0 0 ... 1.0 0.0 38190.78]]


In [78]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [79]:
print(X_train)

[[421 1 1 ... 1.0 1.0 12162.76]
 [579 1 1 ... 1.0 1.0 54816.57]
 [627 0 0 ... 1.0 0.0 125451.01]
 ...
 [669 0 0 ... 1.0 0.0 148611.52]
 [750 1 0 ... 0.0 0.0 19264.33]
 [699 0 1 ... 1.0 0.0 68297.61]]


In [80]:
print(X_test)

[[684 0 0 ... 1.0 1.0 80593.49]
 [635 1 1 ... 1.0 1.0 60739.16]
 [719 1 1 ... 1.0 1.0 176091.31]
 ...
 [616 0 0 ... 1.0 0.0 183840.51]
 [743 0 1 ... 0.0 0.0 113079.19]
 [748 0 0 ... 0.0 0.0 38153.19]]


In [81]:
print(y_test)

[1 0 0 ... 1 1 0]


In [82]:
print(y_train)

[0 0 0 ... 0 0 1]


In [83]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [84]:
print(X_train)

[[-2.40157524  1.73926128  0.89183072 ...  0.65000487  0.96048298
  -1.52506597]
 [-0.75240472  1.73926128  0.89183072 ...  0.65000487  0.96048298
  -0.78680059]
 [-0.2513909  -0.57495674 -1.1106376  ...  0.65000487 -1.04175981
   0.43576222]
 ...
 [ 0.1869962  -0.57495674 -1.1106376  ...  0.65000487 -1.04175981
   0.83663151]
 [ 1.03245704  1.73926128 -1.1106376  ... -1.54027353 -1.04175981
  -1.40214979]
 [ 0.50012985 -0.57495674  0.89183072 ...  0.65000487 -1.04175981
  -0.55346657]]


In [85]:
print(X_test)

[[ 0.34356302 -0.57495674 -1.1106376  ...  0.65000487  0.96048298
  -0.34064566]
 [-0.16788859  1.73926128  0.89183072 ...  0.65000487  0.96048298
  -0.68429056]
 [ 0.70888561  1.73926128  0.89183072 ...  0.65000487  0.96048298
   1.31226025]
 ...
 [-0.36620656 -0.57495674 -1.1106376  ...  0.65000487 -1.04175981
   1.44638581]
 [ 0.95939252 -0.57495674  0.89183072 ... -1.54027353 -1.04175981
   0.22162692]
 [ 1.01158146 -0.57495674 -1.1106376  ... -1.54027353 -1.04175981
  -1.07521554]]


In [86]:

# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [87]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [88]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[744 146]
 [153  83]]


In [89]:
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 82/100

from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 73.45


In [91]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives) 
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/30
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision))

Precision: 0.36


In [92]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/23+11
recall = recall_score(y_test, y_pred, average='macro')
print('Recall: %.3f' % (recall))

Recall: 0.594


In [93]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# (2*0.829*0.906)/0.829+0.906
# calculate score
score = f1_score(y_test, y_pred, average='macro')
print('F-Measure: %.3f' % (score*100))

F-Measure: 59.483


In [94]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/decision_priyanshu_midterm.pkl', 'wb')) 
# Saving model to disk
 

  


[INFO] Saving model...


In [95]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/decision_priyanshu_midterm.pkl','rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test) 

array([0, 0, 0, ..., 1, 0, 0])

In [97]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/decision_priyanshu_midterm.sav'
joblib.dump(classifier, filename)
 
# some time later...
 
# load the model from disk
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(result)

0.7344582593250444


In [99]:
!pip install streamlit

In [100]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [101]:
# Load the pickled model
import pickle
pickle_in = open("/content/drive/My Drive/decision_priyanshu_midterm.pkl","rb")
model=pickle.load(pickle_in)

In [115]:
%%writefile app.py
import streamlit as st 
from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
pickle_in = open("/content/drive/My Drive/decision_priyanshu_midterm.pkl","rb")
model=pickle.load(pickle_in)
dataset= pd.read_csv('/content/drive/My Drive/Priyanshu Jain - Classification Dataset1.csv')
X = dataset.iloc[:,1:10].values

# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NaN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:,3:9]) 
#Replacing missing data with the calculated mean value  
X[:,3:9]= imputer.transform(X[:,3:9])  

# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NaN, strategy= 'constant', fill_value='female', verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 2:3]) 
#Replacing missing data with the constant value  
X[:, 2:3]= imputer.transform(X[:,2:3])  

# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])

# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 2] = labelencoder_X.fit_transform(X[:, 2])

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

def predict_note_authentication(CreditScore,Geography,Gender,Age,Tenure,Balance,HasCrCard,IsActiveMember,EstimatedSalary):
  output= model.predict(sc.transform([[CreditScore,Geography,Gender,Age,Tenure,Balance,HasCrCard,IsActiveMember,EstimatedSalary]]))
  print("Customer will leave =", output)
  if output==[1]:
    prediction="Customer will Leave"
  else:
    prediction="Customer will not Leave"
  print(prediction)
  return prediction
def main():
    
    html_temp = """
   <div class="" style="background-color:blue;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center> 
   <center><p style="font-size:25px;color:white;margin-top:10px;">Machine Learning Midterm Practical Exam</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    st.header("Customer Prediction")
    Age = st.number_input('Insert a Age',18,60)
    CreditScore= st.number_input('Insert a CreditScore',400,1000)
    HasCrCard = st.number_input('Insert a HasCrCard 0 For No 1 For Yes',0,1)
    Tenure = st.number_input('Insert a Tenure',0,20)
    Balance = st.number_input('Insert a Balance',0)
    Gender = st.number_input('Insert 0 For Male 1 For Female ')
    Geography= st.number_input('Insert Geography 0 For France 1 For Spain')
    IsActiveMember= st.number_input('Insert a IsActiveMember 0 For No 1 For Yes',0,1)
    EstimatedSalary= st.number_input('Insert a EstimatedSalary',0)
    
    
    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(CreditScore,Geography,Gender,Age,Tenure,Balance,HasCrCard,IsActiveMember,EstimatedSalary)
      st.success('Model has predicted {}'.format(result))
    if st.button("About"):
      st.subheader("Developed by Priyanshu Jain")
      st.subheader("C-Section,PIET")

if __name__=='__main__':
  main()
   


Overwriting app.py


In [116]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [117]:
!pip install pyngrok


In [118]:
!ngrok authtoken 1rQ8XkYyUBK9R8KvW6wdVZD6HNI_44Zoypk4KP8df9VdpBAuQ


Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [119]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url


<NgrokTunnel: "http://de7bbee776fe.ngrok.io" -> "http://localhost:80">

In [120]:
 !streamlit run --server.port 80 app.py

2021-05-11 08:07:11.285 An update to the [server] config option section was detected. To have these changes be reflected, please restart streamlit.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://34.86.157.28:80

Customer will leave = [0]
Customer will not Leave
  Stopping...


In [ ]:
ngrok.kill()